config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our flats (<%= @flats.count %>)</h1>

<div class="container">
  <div class="cards row">
    <% @flats.each do |flat| %>
      <div class="card col-3">
      <%= flat.name %>
      <i class="fa-brands fa-linkedin"></i>
      <address><%= flat.address %></address>
      <p>🙋 <%= flat.number_of_guests %> 💶 <%= flat.price_per_night %></p>

      <%= link_to "More info", flat_path(flat.id)%>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<%= @flat.name %>

<%= link_to "All flats", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"> %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>